### ISSUE TITLE
ScrollingLabel is broken

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-ui#14]
Hello,

I was trying out the ScrollingLabel as explained in the ScrollingLabel example provided in the documentation [here](https://github.com/rdkcentral/Lightning-ui/blob/main/docs/ScrollingLabel.md). In the documentation there are several examples of usage, but none of them work. For example, if I try the first example in the documentation, the app fails to open and I get an error message:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/18258655/162700262-dca8a12c-2f85-4717-b8c2-75cf9cfc39c9.png">

**Expected Behaviour:**
The app should start, and the label should scroll

**Current Behaviour:**
The app fails to start with a JS error.

I will submit a PR to fix this.

**Comment by jfboeve** [comment]
Issue fixed in version 1.2.4
