### ISSUE TITLE
ScrollingLabel's "autoStart" property not working

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-ui#16]
Hello,

I was trying out the ScrollingLabel as explained in the ScrollingLabel example provided in the documentation [here](https://github.com/rdkcentral/Lightning-ui/blob/main/docs/ScrollingLabel.md). The documentation explains that we can tell the ScrollingLabel to not start scrolling automatically using the property ```autoStart```. This doesn't actually work.

**Steps to reproduce:** 
Use the example from the documentation and set the ```autoStart``` property to false.

Expected Behaviour:
The label should not start scrolling automatically.

Current Behaviour:
The label always starts scrolling automatically, ```autoStart``` property is ignored.

I will submit a PR for this.

**Comment by jfboeve** [comment]
Issue fixed in version 1.2.4
