### ISSUE TITLE
CollectionWrapper documentation not up to date

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-ui#18]
Hi,

I noticed that the documentation for the CollectionWrapper (this one: [LightningJS.io - Documentation](https://lightningjs.io/docs/#/lightning-ui-reference/CollectionWrapper/index) ) is not up to date. Particularly, the section on “Scrolling” > “Customizing” is no longer correct.

However, the same documentation in GitHub CollectionWrapper.md is correct [Lightning-ui/index.md at main · rdkcentral/Lightning-ui](https://github.com/rdkcentral/Lightning-ui/blob/main/docs/CollectionWrapper/index.md) . 

Is it possible to synchronise the documentation with what is in GitHub?

**Comment by jfboeve** [comment]
Status Update: I've notified the person who runs the LightningJS.io site will synchronise the documentation. Will update the ticket when this is done.

**Comment by jfboeve** [comment]
The new synchronisation for the documentation has finally been released. So all the documentation should be up to date now.
