### ISSUE TITLE
Anchored carousel destroys items that are still on screen

### ISSUE THREAD

**Issue by sarahpads** [rdkcentral/Lightning-ui#19]
Steps to produce:
1. Run the https://github.com/mlapps/ui-component-examples app with `@lightningjs/sdk` version 4.8.3 and `@lightningjs/ui` version 1.2.4
2. Update the ImageCell component's static width to 1465; this ensures that the Carousel displays one entire ImageCell component, with both immediate siblings slightly visible on the sides
3. Load the Carousel displayed as Row example
4. Press the left arrow to navigate to the previous item

Expected result: The Carousel slides to the right with the sibling components slightly visible on the sides
Actual result: The Carousel slides to the right, but the left sibling is removed once the transition is complete

I poked around a bit, and it appears that this check (https://github.com/rdkcentral/Lightning-ui/blob/main/src/Carousel.js#L202) is returning true for the left-hand sibling even though it is still on screen. If setting the ImageCell static width to 1464 (1 pixel less than the scenario above) the left sibling remains on screen as expected. See below for the local values depending on the ImageCell width:

ImageCell.width = 1465
boundStart = 1267.2
offset = 1707.5
child[main] = -2975
1707.5 + -2975 < -1267.2 = true (this causes the element to be removed)

ImageCell.width = 1464
boundStart = 1267.2
offset = 1707
child[main] = -2973
1707 + -2973 < -1267.2 = false (this does not mark the element for removal)

Happy to provide any more details and help debug. I have also attached a screen capture of the issue. Thanks!

https://user-images.githubusercontent.com/11469179/164749755-cc09ce2b-c3a4-4401-97f5-65f32057dfbf.mov

**Comment by jfboeve** [comment]
Hi, 

Thanks for pointing out this issue! The issue should be fixed in version 1.2.5.

With kind regards,

Jeffrey

**Comment by sarahpads** [comment]
Works like a charm! Thank you so much for the quick fix 😄
