### ISSUE TITLE
CollectionWrapper: item's marginTop not being applied

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [rdkcentral/Lightning-ui#30]
Hello,

I was trying to use the `marginTop` property on an `List` item and was seen no visual impact. Applying `marginBottom` would work as expected.

After some debugging and digging, I ended up finding these which I believe are some _ancient relics_:

https://github.com/rdkcentral/Lightning-ui/blob/99a220e3e73b66693b5a3fda8596ab2b2ad1174c/src/helpers/ItemWrapper.js#L35-L36

https://github.com/rdkcentral/Lightning-ui/blob/c075a25f6236140a3c211ec0c961991bf6ee0053/src/helpers/CollectionWrapper.js#L363

https://github.com/rdkcentral/Lightning-ui/blob/c075a25f6236140a3c211ec0c961991bf6ee0053/src/helpers/CollectionWrapper.js#L368

These should be `marginTop` I believe, as if I change those to `marginTop` it starts working as expected. I'll submit a PR and merge it if it is indeed an forgotten _ancient relic_.

**Comment by ricardo-a-alves-alb** [comment]
@jfboeve I believe it was you who implemented this, could you check if it sounds good?

**Comment by jfboeve** [comment]
Hey @ricardo-a-alves-alb,

Thanks for this find. It managed to elude me for quite a while! 

Fix is released with version 1.3.2
