### ISSUE TITLE
bug: CollectionWrapper remove method doesn't work

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [rdkcentral/Lightning-ui#32]
Hello,

We were trying to use the `remove()` method available on the `CollectionWrapper` and it doesn't seem to work.

https://github.com/rdkcentral/Lightning-ui/blob/1d9801d26bdcd1a4a17aec495459812702d1d918/src/helpers/CollectionWrapper.js#L132-L143

From our investigation, the culprit seems to be the that `this.wrapper.children` doesn't contain the property `assignedID`.
Using the internal `get items()` seems to fix the issue, because it returns the `component` if it is alive.

https://github.com/rdkcentral/Lightning-ui/blob/1d9801d26bdcd1a4a17aec495459812702d1d918/src/helpers/CollectionWrapper.js#L526-L534

If replacing the blocks that use `this.wrapper.children` with `this.items` seems good to you, I can provide a PR to be merged.

**Comment by jfboeve** [comment]
Thanks for bringing this to my attention. This is fixed in version 1.3.3
