### ISSUE TITLE
Wrong index in Carousel

### ISSUE THREAD

**Issue by fernando-j-afonso-alb** [rdkcentral/Lightning-ui#34]
https://github.com/rdkcentral/Lightning-ui/blob/1d9801d26bdcd1a4a17aec495459812702d1d918/src/Carousel.js#L123

I think this may be wrong. The index is always 3.

**Comment by jfboeve** [comment]
Yeah so the index was more a focus index for the carousel to focus the correct item. I've made some changes so the index is always the data index.
