### ISSUE TITLE
lightningjs/ui vs lightningjs/ui-components

### ISSUE THREAD

**Issue by lukechinworth** [rdkcentral/Lightning-ui#45]
Whats the difference between these?

* https://www.npmjs.com/package/@lightningjs/ui
* https://www.npmjs.com/package/@lightningjs/ui-components
 
I noticed the demo project uses ui-components https://github.com/ComcastSamples/lightning-ui-tmdb
but ui has been updated more recently.

**Comment by michielvandergeest** [comment]
Hi Luke,

In short: they are 2 different UI projects built on Lightning, that have confusingly similar names 😄 

**@lightningjs/ui** is the repo you are looking at now. It’s developed by a member of the Lightning Core team and it’s a collection of base components that you can use in a Lightning App. They are extendable / configurable components and are built with performance in mind

**@lightningjs/ui-components** is a UI library developed within Comcast by Emily Rautenburg and her team. It’s the default library used internally in Comcast for Lightning Apps. The repo on RDK central (https://github.com/rdkcentral/Lightning-UI-Components) contains all the components the team was able open source. Afaik more components are underway to be open sourced, with the upcoming 5.0 release.

Depending on your needs and preferences, you can pick one library or the other. Technically you might even be able to use them at the same, if you’d like 👍 

Hope that helps!

**Comment by lukechinworth** [comment]
Appreciate it. thanks!
