### ISSUE TITLE
CollectionWrapper: initially not requesting more items to fulfill request threshold

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [rdkcentral/Lightning-ui#46]
https://github.com/rdkcentral/Lightning-ui/blob/67472fff84fa630b367d4a57c829018af7e25717/src/helpers/CollectionWrapper.js#L67-L80

Probably the `previous < target` the condition needs to be dropped, because initially it should be triggering request when there are not enough items to reach the request threshold.

In my use-case, I have a grid that has 6 columns and the requests are made with 10 items, which means that if I do the first request and add the first 10 items, it doesn't trigger more requests until I navigate to the second line of the grid.

This change would also let `CollectionWrapper` manage the requests exclusively. As of now, we need to add the first items to the `CollectionWrapper`. If this condition doesn't exist, we only need to provide a `onRequestItems` callback and `CollectionWrapper` does all it needs to do.

**Comment by jfboeve** [comment]
Fix now part of dev branch, will release a new version when #48 has been resolved
