### ISSUE TITLE
CollectionWrapper: Reload items with onRequestItems

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [rdkcentral/Lightning-ui#48]
If #47 gets pushed, it would be beneficial to have a method to reload the entire `CollectionWrapper` so that it triggers the requests from zero.

My use-case would be having an outside filter that when clicked it would need to refresh the `CollectionWrapper` so that it requests new items with this filter applied.

Right now, the only option is to `clear` the items from the `CollectionWrapper`, make the first request and then let `CollectionWrapper` handle the rest.

**Comment by jfboeve** [comment]
@ricardo-a-alves-alb 
I've added the method requestItems(reload, obj), to the dev branch. Could you test it out on your end? I will also test it on my side!

reload parameter is optional, default is false.
obj parameter is also optional, default is {previous: 0, index: 0, max: 0}.

So if you have an outside filter that is changed u can now call MyCollectionWrapper.requestItems(true)

**Comment by ricardo-a-alves-alb** [comment]
Almost perfect. Only thing that still doesn't happen is the recurrent request to fulfill the request threshold. If we change the order of the validation here:

https://github.com/rdkcentral/Lightning-ui/blob/62e9323a8f425350bfc16906e4272b31f20c3cf9/src/helpers/CollectionWrapper.js#L89-L102

To this:

```js
this.signal('onRequestItems', obj)
    .then((response) => {
        if (response === false) {
            this.enableRequests = false;
        }
        this._requestingItems = false;
        if(reload) {
            this.clear();
        }
        const type = typeof response;
        if (Array.isArray(response) || type === 'object' ||  type === 'string' || type === 'number') {
            this.add(response);
        }
    })
```

This way, when we add new items, indexChanged is triggered and requests new items. As of now, since requestingItems flag is set afterwards, when indexChanged is triggered it doesn't request new items.

**Comment by jfboeve** [comment]
Okay updated the code on dev! I'll add it to the documentation and changelog, and run a release by the end of today.

**Comment by ricardo-a-alves-alb** [comment]
Thanks a lot, all looks good to me!

**Comment by jfboeve** [comment]
And released! Thanks for improving the request system!
