### ISSUE TITLE
passwordmode + new implementation for show cursor causes a * to always show

### ISSUE THREAD

**Issue by Sv-Th** [rdkcentral/Lightning-ui#6]
Hi,

Thought i would create an issue regarding the comment i left. Easier to keep track this way.
_Originally posted by @Sv-Th in https://github.com/rdkcentral/Lightning-ui/issues/3#issuecomment-966963641_

One issue with the current implementation is that using the space on line 72 of inputfield ([link](https://github.com/rdkcentral/Lightning-ui/blob/423dbfc00df9b4c777747d347378df53df21366c/src/InputField.js#L72)) to have the cursor position correctly would cause the inputfield to always display a * in passwordmode when empty. My fix to this was [this commit](https://github.com/rdkcentral/Lightning-ui/pull/3/commits/fb7d2c5237a6343d77ccdb8b3ddb49c9a3c81aed) where the render was done on firstactive. 

There could be other ways to solve this, of course.

**Comment by jfboeve** [comment]
Fixed in 1.2.0
