### ISSUE TITLE
CollectionWrapper is throwing the error for all the List Components

### ISSUE THREAD

**Issue by sthirumurugesan** [rdkcentral/Lightning-ui#60]
Details:

- Updated the UI Components this morning
- Currently using 1.3.8
- SDK Version 5.3.2

![Screenshot 2023-05-17 at 12 08 09](https://github.com/rdkcentral/Lightning-ui/assets/87514005/13ebf9df-cec2-43f1-b8fc-22889af6a406)

**Comment by ricardo-a-alves-alb** [comment]
Hello there, if you can, test out the PR I just submitted to see if it fixes your issues. Thanks!

**Comment by sthirumurugesan** [comment]
Hello, Yes i have tested in my local machine and it's working fine now. Thanks for the quick fix.

**Comment by jfboeve** [comment]
Sorry for the late response! Thank you Ricardo for the awesome work once again!
