### ISSUE TITLE
Grid - newItem exception when trying to reposition

### ISSUE THREAD

**Issue by daniel-g-favoreto-opl** [rdkcentral/Lightning-ui#69]
When trying to reposition the grid from inside a card with this.collectionWrapper.reposition(), a exception is throw saying that newItem was not initialized. It seems to me that this property is missing.
![image](https://github.com/rdkcentral/Lightning-ui/assets/112583028/ec8462b1-3f1e-407e-955c-2c9efd296f17)

**Comment by jfboeve** [comment]
This issue is fixed in v1.3.16, seemed to be a classic case of reusing code I used when plotting items on my part. Obviously during the reposition event we are not really expecting new items.
